// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/customers/print": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/api/customers": {
    params: {};
  };
  "/api/sync-clover": {
    params: {};
  };
  "/api/cache": {
    params: {};
  };
  "/api/cache-status": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/customers" | "/customers/print" | "/admin" | "/api/customers" | "/api/sync-clover" | "/api/cache" | "/api/cache-status";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/customers";
  };
  "routes/customers.print.tsx": {
    id: "routes/customers.print";
    page: "/customers/print";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/api.customers.tsx": {
    id: "routes/api.customers";
    page: "/api/customers";
  };
  "routes/api.sync-clover.tsx": {
    id: "routes/api.sync-clover";
    page: "/api/sync-clover";
  };
  "routes/api.cache.tsx": {
    id: "routes/api.cache";
    page: "/api/cache";
  };
  "routes/api.cache-status.tsx": {
    id: "routes/api.cache-status";
    page: "/api/cache-status";
  };
};